kind: pipeline
type: docker
name: Docker插件


clone:
  disable: true


trigger:
  event:
    exclude:
      - pull_request


steps:
  - name: 拉代码
    image: dronestock/git
    pull: always

  - name: 编译
    image: pangum/drone
    pull: always
    settings:
      output: docker

  - name: 打包Docker到中央库
    image: dronestock/docker
    pull: always
    privileged: true
    volumes:
      - name: cache
        path: /var/lib/docker
    settings:
      repository: dronestock/docker
      username: dronestock
      password:
        from_secret: token_docker


volumes:
  - name: cache
    host:
      path: /var/lib/cache/docker
