kind: pipeline
type: docker
name: Drone持续集成Docker插件


clone:
  disable: true


trigger:
  event:
    exclude:
      - pull_request


steps:
  - name: 拉代码
    image: ccr.ccs.tencentyun.com/dronestock/git
    pull: always
    settings:
      verbose: true
      debug: true
      ssh_key:
        from_secret: ssh_key_github

  - name: 编译
    image: dronestock/pangu
    pull: if-not-exists
    settings:
      output: dockerd
      verbose: true

  - name: 打包Docker到中央库
    image: ccr.ccs.tencentyun.com/dronestock/docker
    pull: if-not-exists
    volumes:
      - name: cache
        path: /var/lib/docker
    privileged: true
    settings:
      repository: dronestock/docker
      username: dronestock
      password:
        from_secret: token_docker


volumes:
  - name: cache
    host:
      path: /var/lib/docker
