kind: secret
name: token_docker
get:
  path: secrets
  name: token_docker_dronestock
---

kind: secret
name: password_ccr
get:
  path: secrets
  name: password_ccr
---


kind: pipeline
type: docker
name: 发布


clone:
  disable: true


environment:
  NAME: docker
  OUTPUT_LINUX: docker.amd64.lin
  OUTPUT_WINDOWS: docker.amd64.exe
  OUTPUT_MAC: docker.amd64.mac
  CHANGELOG_TAG_OUTPUT: CHANGELOG.tag.md


steps:
  - name: 代码
    image: ccr.ccs.tencentyun.com/dronestock/git
    pull: always

  - name: 编译
    image: ccr.ccs.tencentyun.com/pangum/drone
    pull: always
    volumes:
      - name: go
        path: /var/lib/go
    settings:
      outputs:
        - name: docker/bin/$${NAME}
          os: linux
          arch: amd64
        - name: docker/bin/$${OUTPUT_LINUX}
          os: linux
          arch: amd64
        - name: docker/bin/$${OUTPUT_WINDOWS}
          os: windows
          arch: amd64
        - name: docker/bin/$${OUTPUT_MAC}
          os: darwin
          arch: amd64

  - name: 推送
    image: ccr.ccs.tencentyun.com/dronestock/docker
    pull: always
    privileged: true
    volumes:
      - name: go
        path: /var/lib/go
    environment:
      PASSWORD_DOCKER:
        from_secret: token_docker
      PASSWORD_CCR:
        from_secret: password_ccr
    settings:
      repository: dronestock/docker
      registries:
        - username: dronestock
          password: $${PASSWORD_DOCKER}
        - hostname: ccr.ccs.tencentyun.com
          username: "160290688"
          password: $${PASSWORD_CCR}
          required: true

  - name: 改变
    image: ccr.ccs.tencentyun.com/dronestock/changelog
    pull: always
    when:
      event:
        - tag
    settings:
      output: $${CHANGELOG_TAG_OUTPUT}
      tag: $${DRONE_TAG}

  - name: 发布
    image: ccr.ccs.tencentyun.com/dronestock/github
    pull: always
    when:
      event:
        - tag
    environment:
      VERSION: $${DRONE_TAG##v}
      TOKEN:
        from_secret: token_github
    settings:
      release:
        tag: $${DRONE_TAG}
        token: $${TOKEN}
        body: expr:file("$${CHANGELOG_TAG_OUTPUT}")
        assets:
          - name: $${NAME}-$${VERSION}-linux-amd64
            file: docker/bin/$${OUTPUT_LINUX}
          - name: $${NAME}-$${VERSION}-windows-amd64.exe
            file: docker/bin/$${OUTPUT_WINDOWS}
          - name: $${NAME}-$${VERSION}-darwin-amd64
            file: docker/bin/$${OUTPUT_MAC}


volumes:
  - name: docker
    host:
      path: /var/lib/cache/docker
  - name: go
    host:
      path: /var/lib/cache/go
