kind: pipeline
type: docker
name: Docker插件


clone:
  disable: true


environment:
  NAME: docker
  OUTPUT_LINUX: docker.amd64.lin
  OUTPUT_WINDOWS: docker.amd64.exe
  OUTPUT_MAC: docker.amd64.mac
  CHANGELOG_TAG_OUTPUT: CHANGELOG.tag.md


steps:
  - name: 代码
    image: ccr.ccs.tencentyun.com/dronestock/git

  - name: 编译
    image: ccr.ccs.tencentyun.com/pangum/drone
    volumes:
      - name: go
        path: /var/lib/go
    settings:
      outputs:
        - name: $${NAME}
          os: linux
          arch: amd64
        - name: $${OUTPUT_LINUX}
          os: linux
          arch: amd64
        - name: $${OUTPUT_WINDOWS}
          os: windows
          arch: amd64
        - name: $${OUTPUT_MAC}
          os: darwin
          arch: amd64

  - name: 推送
    image: ccr.ccs.tencentyun.com/dronestock/docker
    privileged: true
    volumes:
      - name: gopath
        path: /var/lib/gopath
      - name: gocache
        path: /var/lib/gocache
      - name: linter
        path: /var/lib/linter
    environment:
      PASSWORD_DOCKER:
        from_secret: token_docker
      PASSWORD_CCR:
        from_secret: password_tencentyun_ccr
    settings:
      repository: dronestock/docker
      registries:
        - username: dronestock
          password: $${PASSWORD_DOCKER}
        - hostname: ccr.ccs.tencentyun.com
          username: "160290688"
          password: $${PASSWORD_CCR}
          required: true

  - name: 改变
    image: ccr.ccs.tencentyun.com/dronestock/changelog
    when:
      event:
        - tag
    settings:
      output: $${CHANGELOG_TAG_OUTPUT}
      tag: $${DRONE_TAG}

  - name: 发布
    image: ccr.ccs.tencentyun.com/dronestock/github
    when:
      event:
        - tag
    environment:
      VERSION: $${DRONE_TAG##v}
      TOKEN:
        from_secret: token_github
    settings:
      release:
        tag: $${DRONE_TAG}
        token: $${TOKEN}
        body: expr:file("$${CHANGELOG_TAG_OUTPUT}")
        assets:
          - name: $${NAME}-$${VERSION}-linux-amd64
            file: $${OUTPUT_LINUX}
          - name: $${NAME}-$${VERSION}-windows-amd64.exe
            file: $${OUTPUT_WINDOWS}
          - name: $${NAME}-$${VERSION}-darwin-amd64
            file: $${OUTPUT_MAC}


volumes:
  - name: docker
    host:
      path: /var/lib/cache/docker
  - name: gopath
    host:
      path: /var/lib/cache/gopath
  - name: gocache
    host:
      path: /var/lib/cache/gocache
  - name: linter
    host:
      path: /var/lib/cache/linter
